name: Deploy Lambda Function

on:
  workflow_dispatch:  # Manual trigger via GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t package
        cp monitor.py package/
        cd package && zip -r ../lambda_function.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name monitor_script \
          --zip-file fileb://lambda_function.zip
